// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeRentApp.Data;

#nullable disable

namespace OfficeRentApp.Migrations
{
    [DbContext(typeof(OfficeRentDbContext))]
    [Migration("20230420072008_officeNullable")]
    partial class officeNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OfficeRentApp.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "44 Jafar Jabbarli street, Baku 1065",
                            BuildingName = "Caspian Plaza",
                            Floor = 8,
                            IsEmpty = true,
                            PricePerHour = 60m
                        },
                        new
                        {
                            Id = 2,
                            Address = "44 Jafar Jabbarli street, Baku 1065",
                            BuildingName = "Caspian Plaza",
                            Floor = 15,
                            IsEmpty = true,
                            PricePerHour = 85m
                        },
                        new
                        {
                            Id = 3,
                            Address = "44 Jafar Jabbarli street, Baku 1065",
                            BuildingName = "Caspian Plaza",
                            Floor = 3,
                            IsEmpty = true,
                            PricePerHour = 40m
                        });
                });

            modelBuilder.Entity("OfficeRentApp.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EndOfRent")
                        .HasColumnType("datetime2");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartOfRent")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("OfficeRentApp.Models.Rental", b =>
                {
                    b.HasOne("OfficeRentApp.Models.Office", "Office")
                        .WithMany("Rental")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("OfficeRentApp.Models.Office", b =>
                {
                    b.Navigation("Rental");
                });
#pragma warning restore 612, 618
        }
    }
}
